    catch_phrase() = join(map( x -> select_random(x)*" " , data["faker"]["company"]["buzzwords"] ))
    bs() = join(map( x -> select_random(x)*" " , data["faker"]["company"]["bs"] ))
    company_suffix()= select_random(data["faker"]["company"]["suffix"])
    company_prefix() = select_random(data["faker"]["company"]["prefix"])
    company()=executor(data["faker"]["company"]["name"])