    catch_phrase()::String  = join(map( x -> select_random(x)*" " , data["faker"]["company"]["buzzwords"] ))
    bs()::String = join(map( x -> select_random(x)*" " , data["faker"]["company"]["bs"] ))
    company_suffix()::String = select_random(data["faker"]["company"]["suffix"])
    company_prefix()::String  = select_random(data["faker"]["company"]["prefix"])
    company()::String =executor(data["faker"]["company"]["name"])